services:
  wp:
    image: wordpress:latest
    container_name: site7_wp
    ports:
      - "8007:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wpuserpass
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./wp-config.php.bak:/var/www/html/wp-config.php.bak

  db:
    image: mysql:5.7
    container_name: site7_db
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wpuserpass
      MYSQL_ROOT_PASSWORD: rootpass
