services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${GABRIELA_ONOFREI_DB_PASS}
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${GABRIELA_ONOFREI_DB_PASS}
      MYSQL_ROOT_PASSWORD: ${GABRIELA_ONOFREI_DB_ROOT_PASS}
