name: WPScan Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
          -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Export DB secrets
      run: |
        echo "GABRIELA_ONOFREI_DB_PASS=${{ secrets.GABRIELA_ONOFREI_DB_PASS }}" >>"$GITHUB_ENV"
        echo "GABRIELA_ONOFREI_DB_ROOT_PASS=${{ secrets.GABRIELA_ONOFREI_DB_ROOT_PASS }}" >>"$GITHUB_ENV"

    - name: Loop through WordPress sites
      env:
        WPSCAN_API_TOKEN: ${{ secrets.GABRIELA_ONOFREI_WPSCAN_API_TOKEN }}
      run: |
        set -e

        for site in site4-backup ; do

          echo "Starting ${site}"

          compose_file="${site}/info.yml"

          docker-compose -f "$compose_file" up -d

          sleep 35

          echo "Installing WP-CLI"
          docker exec wordpress bash -c '
            if ! command -v wp >/dev/null 2>&1; then
              apt update -qq && apt install -y -qq curl unzip less mariadb-client
              curl -s -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
              chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp
            fi'

          echo "Installing wp core"
          docker exec wordpress wp core install \
              --url="http://localhost:8000" \
              --title="${site}" \
              --admin_user="admin" \
              --admin_password="ParolaMeaDeAdmin" \
              --admin_email="admin@example.com" \
              --skip-email --allow-root >/dev/null

          if [[ "$site" == "site6-plugin/" ]]; then
            echo "Activating hello-dolly plugin"
            docker exec wordpress wp plugin activate hello-dolly --allow-root || true
          fi

          echo "WPScan on ${site}"
          docker run --rm wpscanteam/wpscan \
              --url http://host.docker.internal:8000 \
              --api-token "$WPSCAN_API_TOKEN" \
              --disable-tls-checks \
              --enumerate u || true

          echo "docker-compose down"
          docker-compose -f "$compose_file" down -v

        done
