name: WPScan Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Export DB secrets
      run: |
        echo "GABRIELA_ONOFREI_DB_PASS=${{ secrets.GABRIELA_ONOFREI_DB_PASS }}" >> $GITHUB_ENV
        echo "GABRIELA_ONOFREI_DB_ROOT_PASS=${{ secrets.GABRIELA_ONOFREI_DB_ROOT_PASS }}" >> $GITHUB_ENV

    - name: Loop through WordPress sites
      env:
        WPSCAN_API_TOKEN: ${{ secrets.GABRIELA_ONOFREI_WPSCAN_API_TOKEN }}
      run: |
        for site in site4-backup/; do

          echo "Starting $site"
          docker-compose -f "$site/info.yml" up -d

          echo "Waiting for WordPress ($site)..."
          sleep 30

          echo "Installing WP CLI"
          docker exec wordpress bash -c "\
            apt update && \
            apt install -y curl unzip mariadb-client less && \
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
            chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp"

          echo "Installing WordPress core"
          docker exec wordpress wp core install \
            --url="http://localhost:8000" \
            --title="${site%/}" \
            --admin_user="admin" \
            --admin_password="ParolaMeaDeAdmin" \
            --admin_email="admin@example.com" \
            --skip-email \
            --allow-root


          if [[ "$site" == "site6-plugin/" ]]; then
            echo "Installing vulnerable plugin on $site"
            docker exec wordpress wp plugin install hello-dolly --activate --allow-root || echo "Plugin not found"
          fi

          echo "Scanning with WPScan ($site)"
          docker run --rm --network ${site%/}_default wpscanteam/wpscan \
            --url http://wordpress \
            --api-token $WPSCAN_API_TOKEN \
            --disable-tls-checks \
            --enumerate vp,u || true

          echo "Cleaning up $site"
          docker-compose -f "$site/info.yml" down
        done
