name: WPScan Workflow

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install the Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Start WordPress
      run: |
        docker-compose -f info.yml up -d
        sleep 40

    - name: Run WPScan
      env:
        WPSCAN_API_TOKEN: ${{ secrets.GABRIELA_ONOFREI_WPSCAN_API_TOKEN }}
      run: |
        docker run --rm wpscanteam/wpscan \
          --url http://host.docker.internal:8000 \
          --api-token $WPSCAN_API_TOKEN \
          --disable-tls-checks

    - name: Cleaning
      run: docker-compose -f info.yml down
